//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEXiled.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEXiled.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EXILED\:ABSOLUTE
        ///Assembly-CSharp.dll:GAME
        ///.
        /// </summary>
        internal static string Markup {
            get {
                return ResourceManager.GetString("Markup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does it exist? - {0}.
        /// </summary>
        internal static string Program_EnsureDirExists_Does_it_exist_____0_ {
            get {
                return ResourceManager.GetString("Program_EnsureDirExists_Does_it_exist_____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensuring directory path: {0}.
        /// </summary>
        internal static string Program_EnsureDirExists_Ensuring_directory_path___0_ {
            get {
                return ResourceManager.GetString("Program_EnsureDirExists_Ensuring_directory_path___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An exception occurred while trying to extract a file.
        /// </summary>
        internal static string Program_ExtractEntry_An_exception_occurred_while_trying_to_extract_a_file {
            get {
                return ResourceManager.GetString("Program_ExtractEntry_An_exception_occurred_while_trying_to_extract_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting &apos;{0}&apos; into &apos;{1}&apos;....
        /// </summary>
        internal static string Program_ExtractEntry_Extracting___0___into___1_____ {
            get {
                return ResourceManager.GetString("Program_ExtractEntry_Extracting___0___into___1_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- ASSETS ---.
        /// </summary>
        internal static string Program_MainSafe_____ASSETS____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____ASSETS____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- AVAILABLE VERSIONS ---.
        /// </summary>
        internal static string Program_MainSafe_____AVAILABLE_VERSIONS____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____AVAILABLE_VERSIONS____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- RELEASES ---.
        /// </summary>
        internal static string Program_MainSafe_____RELEASES____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____RELEASES____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AppData folder: {0}.
        /// </summary>
        internal static string Program_MainSafe_AppData_folder___0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_AppData_folder___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Asset found!.
        /// </summary>
        internal static string Program_MainSafe_Asset_found_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Asset_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t find &apos;{0}&apos; in &apos;{1}&apos;.
        /// </summary>
        internal static string Program_MainSafe_Couldn_t_find___0___in___1__ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Couldn_t_find___0___in___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installation complete.
        /// </summary>
        internal static string Program_MainSafe_Installation_complete {
            get {
                return ResourceManager.GetString("Program_MainSafe_Installation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prereleases included - {0}.
        /// </summary>
        internal static string Program_MainSafe_Prereleases_included____0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Prereleases_included____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read the exception message, read the readme, and if you still don&apos;t understand what to do, then contact #support in our discord server with the attached screenshot of the full exception.
        /// </summary>
        internal static string Program_MainSafe_Read_the_exception_message__read_the_readme__and_if_you_still_don_t_understand_what_to_do__then_contact__support_in_our_discord_server_with_the_attached_screenshot_of_the_full_exception {
            get {
                return ResourceManager.GetString("Program_MainSafe_Read_the_exception_message__read_the_readme__and_if_you_still_do" +
                        "n_t_understand_what_to_do__then_contact__support_in_our_discord_server_with_the_" +
                        "attached_screenshot_of_the_full_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receiving releases....
        /// </summary>
        internal static string Program_MainSafe_Receiving_releases___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Receiving_releases___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Release found!.
        /// </summary>
        internal static string Program_MainSafe_Release_found_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Release_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching for the latest release that matches the parameters....
        /// </summary>
        internal static string Program_MainSafe_Searching_for_the_latest_release_that_matches_the_parameters___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Searching_for_the_latest_release_that_matches_the_parameters___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target release version - {0}.
        /// </summary>
        internal static string Program_MainSafe_Target_release_version____0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Target_release_version____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Token detected! Using the token....
        /// </summary>
        internal static string Program_MainSafe_Token_detected__Using_the_token___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Token_detected__Using_the_token___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t resolve path for &apos;{0}&apos;, update installer.
        /// </summary>
        internal static string Program_ProcessTarEntry_Couldn_t_resolve_path_for___0____update_installer {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Couldn_t_resolve_path_for___0____update_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract for {0} is disabled.
        /// </summary>
        internal static string Program_ProcessTarEntry_Extract_for__0__is_disabled {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Extract_for__0__is_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Processing &apos;{0}&apos;.
        /// </summary>
        internal static string Program_ProcessTarEntry_Processing___0__ {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Processing___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trying to find release...
        /// </summary>
        internal static string Program_TryFindRelease_Trying_to_find_release__ {
            get {
                return ResourceManager.GetString("Program_TryFindRelease_Trying_to_find_release__", resourceCulture);
            }
        }
    }
}
