//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exiled.Installer.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Exiled.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Markup {
            get {
                return ResourceManager.GetString("Markup", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Receiving_releases___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Receiving_releases___", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Prereleases_included____0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Prereleases_included____0_", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Target_release_version____0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Target_release_version____0_", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Searching_for_the_latest_release_that_matches_the_parameters___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Searching_for_the_latest_release_that_matches_the_parameters___", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_____RELEASES____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____RELEASES____", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Release_found_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Release_found_", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_____ASSETS____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____ASSETS____", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Asset_found_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Asset_found_", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Installation_complete {
            get {
                return ResourceManager.GetString("Program_MainSafe_Installation_complete", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Read_the_exception_message__read_the_readme__and_if_you_still_don_t_understand_what_to_do__then_contact__support_in_our_discord_server_with_the_attached_screenshot_of_the_full_exception {
            get {
                return ResourceManager.GetString("Program_MainSafe_Read_the_exception_message__read_the_readme__and_if_you_still_do" +
                        "n_t_understand_what_to_do__then_contact__support_in_our_discord_server_with_the_" +
                        "attached_screenshot_of_the_full_exception", resourceCulture);
            }
        }
        
        internal static string Program_ProcessTarEntry_Processing___0__ {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Processing___0__", resourceCulture);
            }
        }
        
        internal static string Program_ProcessTarEntry_Extract_for__0__is_disabled {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Extract_for__0__is_disabled", resourceCulture);
            }
        }
        
        internal static string Program_ProcessTarEntry_Couldn_t_resolve_path_for___0____update_installer {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Couldn_t_resolve_path_for___0____update_installer", resourceCulture);
            }
        }
        
        internal static string Program_ExtractEntry_Extracting___0___into___1_____ {
            get {
                return ResourceManager.GetString("Program_ExtractEntry_Extracting___0___into___1_____", resourceCulture);
            }
        }
        
        internal static string Program_ExtractEntry_An_exception_occurred_while_trying_to_extract_a_file {
            get {
                return ResourceManager.GetString("Program_ExtractEntry_An_exception_occurred_while_trying_to_extract_a_file", resourceCulture);
            }
        }
        
        internal static string Program_EnsureDirExists_Ensuring_directory_path___0_ {
            get {
                return ResourceManager.GetString("Program_EnsureDirExists_Ensuring_directory_path___0_", resourceCulture);
            }
        }
        
        internal static string Program_EnsureDirExists_Does_it_exist_____0_ {
            get {
                return ResourceManager.GetString("Program_EnsureDirExists_Does_it_exist_____0_", resourceCulture);
            }
        }
        
        internal static string Program_TryFindRelease_Trying_to_find_release__ {
            get {
                return ResourceManager.GetString("Program_TryFindRelease_Trying_to_find_release__", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_____AVAILABLE_VERSIONS____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____AVAILABLE_VERSIONS____", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_AppData_folder___0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_AppData_folder___0_", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Couldn_t_find___0___in___1__ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Couldn_t_find___0___in___1__", resourceCulture);
            }
        }
        
        internal static string Program_MainSafe_Token_detected__Using_the_token___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Token_detected__Using_the_token___", resourceCulture);
            }
        }
    }
}
