//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exiled.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exiled.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXILED\:EXILED
        ///SCP Secret Laboratory\:ABSOLUTE
        ///.
        /// </summary>
        internal static string Markup {
            get {
                return ResourceManager.GetString("Markup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it exist? - {0}.
        /// </summary>
        internal static string Program_EnsureDirExists_Does_it_exist_____0_ {
            get {
                return ResourceManager.GetString("Program_EnsureDirExists_Does_it_exist_____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring directory path: {0}.
        /// </summary>
        internal static string Program_EnsureDirExists_Ensuring_directory_path___0_ {
            get {
                return ResourceManager.GetString("Program_EnsureDirExists_Ensuring_directory_path___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while trying to extract a file.
        /// </summary>
        internal static string Program_ExtractEntry_An_exception_occurred_while_trying_to_extract_a_file {
            get {
                return ResourceManager.GetString("Program_ExtractEntry_An_exception_occurred_while_trying_to_extract_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting &apos;{0}&apos; into &apos;{1}&apos;....
        /// </summary>
        internal static string Program_ExtractEntry_Extracting___0___into___1_____ {
            get {
                return ResourceManager.GetString("Program_ExtractEntry_Extracting___0___into___1_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- ASSETS ---.
        /// </summary>
        internal static string Program_MainSafe_____ASSETS____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____ASSETS____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- AVAILABLE VERSIONS ---.
        /// </summary>
        internal static string Program_MainSafe_____AVAILABLE_VERSIONS____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____AVAILABLE_VERSIONS____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- RELEASES ---.
        /// </summary>
        internal static string Program_MainSafe_____RELEASES____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____RELEASES____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData folder: {0}.
        /// </summary>
        internal static string Program_MainSafe_AppData_folder___0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_AppData_folder___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset found!.
        /// </summary>
        internal static string Program_MainSafe_Asset_found_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Asset_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find &apos;{0}&apos; in &apos;{1}&apos;.
        /// </summary>
        internal static string Program_MainSafe_Couldn_t_find___0___in___1__ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Couldn_t_find___0___in___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiled folder: {0}.
        /// </summary>
        internal static string Program_MainSafe_Exiled_folder___0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Exiled_folder___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete.
        /// </summary>
        internal static string Program_MainSafe_Installation_complete {
            get {
                return ResourceManager.GetString("Program_MainSafe_Installation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prereleases included - {0}.
        /// </summary>
        internal static string Program_MainSafe_Prereleases_included____0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Prereleases_included____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the exception message, read the readme, and if you still don&apos;t understand what to do, then contact #support in our discord server with the attached screenshot of the full exception.
        /// </summary>
        internal static string Program_MainSafe_Read_the_exception_message__read_the_readme__and_if_you_still_don_t_understand_what_to_do__then_contact__support_in_our_discord_server_with_the_attached_screenshot_of_the_full_exception {
            get {
                return ResourceManager.GetString("Program_MainSafe_Read_the_exception_message__read_the_readme__and_if_you_still_do" +
                        "n_t_understand_what_to_do__then_contact__support_in_our_discord_server_with_the_" +
                        "attached_screenshot_of_the_full_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving releases....
        /// </summary>
        internal static string Program_MainSafe_Receiving_releases___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Receiving_releases___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release found!.
        /// </summary>
        internal static string Program_MainSafe_Release_found_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Release_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for the latest release that matches the parameters....
        /// </summary>
        internal static string Program_MainSafe_Searching_for_the_latest_release_that_matches_the_parameters___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Searching_for_the_latest_release_that_matches_the_parameters___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code is not success: {0}. The release won&apos;t be installed. Most likely it happened because of the rate limit. You can expand the number of allowed requests per hour by specifying a GitHub token.
        /// </summary>
        internal static string Program_MainSafe_Status_code_is_not_success {
            get {
                return ResourceManager.GetString("Program_MainSafe_Status_code_is_not_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target release version - {0}.
        /// </summary>
        internal static string Program_MainSafe_Target_release_version____0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Target_release_version____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token detected! Using the token....
        /// </summary>
        internal static string Program_MainSafe_Token_detected__Using_the_token___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Token_detected__Using_the_token___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t resolve path for &apos;{0}&apos;, update installer.
        /// </summary>
        internal static string Program_ProcessTarEntry_Couldn_t_resolve_path_for___0____update_installer {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Couldn_t_resolve_path_for___0____update_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract for {0} is disabled.
        /// </summary>
        internal static string Program_ProcessTarEntry_Extract_for__0__is_disabled {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Extract_for__0__is_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &apos;{0}&apos;.
        /// </summary>
        internal static string Program_ProcessTarEntry_Processing___0__ {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Processing___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to find release...
        /// </summary>
        internal static string Program_TryFindRelease_Trying_to_find_release__ {
            get {
                return ResourceManager.GetString("Program_TryFindRelease_Trying_to_find_release__", resourceCulture);
            }
        }
    }
}
