//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exiled.Installer.Properties {
    using System;


    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exiled.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a EXILED\:EXILED
        ///SCP Secret Laboratory\:ABSOLUTE
        ///.
        /// </summary>
        internal static string Markup {
            get {
                return ResourceManager.GetString("Markup", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Does it exist? - {0}.
        /// </summary>
        internal static string Program_EnsureDirExists_Does_it_exist_____0_ {
            get {
                return ResourceManager.GetString("Program_EnsureDirExists_Does_it_exist_____0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Ensuring directory path: {0}.
        /// </summary>
        internal static string Program_EnsureDirExists_Ensuring_directory_path___0_ {
            get {
                return ResourceManager.GetString("Program_EnsureDirExists_Ensuring_directory_path___0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a An exception occurred while trying to extract a file.
        /// </summary>
        internal static string Program_ExtractEntry_An_exception_occurred_while_trying_to_extract_a_file {
            get {
                return ResourceManager.GetString("Program_ExtractEntry_An_exception_occurred_while_trying_to_extract_a_file", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Extracting &apos;{0}&apos; into &apos;{1}&apos;....
        /// </summary>
        internal static string Program_ExtractEntry_Extracting___0___into___1_____ {
            get {
                return ResourceManager.GetString("Program_ExtractEntry_Extracting___0___into___1_____", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a --- ASSETS ---.
        /// </summary>
        internal static string Program_MainSafe_____ASSETS____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____ASSETS____", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a --- AVAILABLE VERSIONS ---.
        /// </summary>
        internal static string Program_MainSafe_____AVAILABLE_VERSIONS____ {
            get {
                return ResourceManager.GetString("Program_MainSafe_____AVAILABLE_VERSIONS____", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a AppData folder: {0}.
        /// </summary>
        internal static string Program_MainSafe_AppData_folder___0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_AppData_folder___0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Asset found!.
        /// </summary>
        internal static string Program_MainSafe_Asset_found_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Asset_found_", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Exiled folder: {0}.
        /// </summary>
        internal static string Program_MainSafe_Exiled_folder___0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Exiled_folder___0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Installation complete.
        /// </summary>
        internal static string Program_MainSafe_Installation_complete {
            get {
                return ResourceManager.GetString("Program_MainSafe_Installation_complete", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Prereleases included - {0}.
        /// </summary>
        internal static string Program_MainSafe_Prereleases_included____0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Prereleases_included____0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Read the exception message, read the readme, and if you still don&apos;t understand what to do, then contact #support in our discord server with the attached screenshot of the full exception.
        /// </summary>
        internal static string Program_MainSafe_Read_the_exception_message__read_the_readme__and_if_you_still_don_t_understand_what_to_do__then_contact__support_in_our_discord_server_with_the_attached_screenshot_of_the_full_exception {
            get {
                return ResourceManager.GetString("Program_MainSafe_Read_the_exception_message__read_the_readme__and_if_you_still_do" +
                        "n_t_understand_what_to_do__then_contact__support_in_our_discord_server_with_the_" +
                        "attached_screenshot_of_the_full_exception", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Receiving releases....
        /// </summary>
        internal static string Program_MainSafe_Receiving_releases___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Receiving_releases___", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Release found!.
        /// </summary>
        internal static string Program_MainSafe_Release_found_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Release_found_", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Searching for the latest release that matches the parameters....
        /// </summary>
        internal static string Program_MainSafe_Searching_for_the_latest_release_that_matches_the_parameters___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Searching_for_the_latest_release_that_matches_the_parameters___", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Target release version - {0}.
        /// </summary>
        internal static string Program_MainSafe_Target_release_version____0_ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Target_release_version____0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Token detected! Using the token....
        /// </summary>
        internal static string Program_MainSafe_Token_detected__Using_the_token___ {
            get {
                return ResourceManager.GetString("Program_MainSafe_Token_detected__Using_the_token___", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Couldn&apos;t resolve path for &apos;{0}&apos;, update installer.
        /// </summary>
        internal static string Program_ProcessTarEntry_Couldn_t_resolve_path_for___0____update_installer {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Couldn_t_resolve_path_for___0____update_installer", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Extract for {0} is disabled.
        /// </summary>
        internal static string Program_ProcessTarEntry_Extract_for__0__is_disabled {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Extract_for__0__is_disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Processing &apos;{0}&apos;.
        /// </summary>
        internal static string Program_ProcessTarEntry_Processing___0__ {
            get {
                return ResourceManager.GetString("Program_ProcessTarEntry_Processing___0__", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Trying to find release...
        /// </summary>
        internal static string Program_TryFindRelease_Trying_to_find_release__ {
            get {
                return ResourceManager.GetString("Program_TryFindRelease_Trying_to_find_release__", resourceCulture);
            }
        }
    }
}
